config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'noodles#index'
  resources :noodles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_header.html.erb
<!-- <nav class="navbar navbar-default "> -->
<div class="container-fluid head">
    <a class="navbar-brand" href="/">
        <%= image_tag "logo.png", size: "60x60", class: "logo" %>
    </a>
    <div class="collapse navbar-collapse bar" id="navbarEexample3">
        <form class="navbar-form hashtag" role="search">
          	<div class="form-group">
                <input type="text" name="hashtag" value="ハッシュタグ(全体)" class="form-size">
          	</div>
          	<button type="submit" class="btn btn-default">検索</button>
        </form>
        <form class="navbar-form kensaku" role="search">
          	<div class="form-group">
				<select name="genre" size="1" class="form-size">
                    <option value="">ジャンル</option>
                    <option value="1">豚骨</option>
                    <option value="2">家系</option>
                    <option value="3">二郎系</option>
                    <option value="4">まぜそば</option>
                    <option value="5">つけ麺</option>
                    <option value="6">醤油</option>
                    <option value="7">味噌</option>
                    <option value="8">塩</option>
                    <option value="9">タンメン</option>
                    <option value="10">その他</option>
                </select>
          	</div>
          	<button type="submit" class="btn btn-default">検索</button>
        </form>
        <div class="tabs">
        <% if user_signed_in?%>
            <% if request.fullpath == "/users" %>
                <a href="/" class="btn btns">全てのユーザーの投稿をみる</a>
            <% else%>
                <a href="/users" class="btn btns">フォローしているユーザーの投稿をみる</a>
            <% end %>
        <% end%>
        </div>
    </div>
</div>

app/views/shared/_like_form.html.erb
<% if user_signed_in? %>
    <% if post.user_liked?(current_user.id) %>
        <%= link_to noodle_like_path(noodle_id: post.id, id: current_user.id), method: :delete, id: "like-button" do %>
            <%= fa_icon 'heart', class: "red-heart btn"%>
        <% end %>
        <span><%= post.likes_count %>件のいいね</span>
    <% else %>
        <%= link_to noodle_likes_path(noodle_id: post.id), method: :post, id: "like-button" do %>
            <%= fa_icon 'heart', class: "btn btns" %>
        <% end %>
        <span><%= post.likes_count %>件のいいね</span>
    <% end %>
<% else %>
    <%= fa_icon 'heart', class: "btn btns" %>
    <span><%= post.likes_count %>件のいいね</span>
<% end %>

app/views/shared/_post.html.erb
<ul class="list-group">
    <li class="list-group-item" id="list1">
        <% if user_signed_in?%>
            <%= link_to user_path(id: post.user.id) do%>
                <%= image_tag post.user.avatar,:class => "icon", :size => "50x50"%>
                <%= post.user.nickname %>
            <% end%>
        <% else%>
            <%= image_tag post.user.avatar,:class => "icon", :size => "50x50"%>
            <%= post.user.nickname %>
        <% end%>

    </li>
    <li class="list-group-item" id="list3">
        <% if post.impressions.include?("#") || post.impressions.include?("＃")%>
            <% hashs = post.impressions.scan(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/)%>
            <%= post.impressions.gsub!(/[#＃][Ａ-Ｚａ-ｚA-Za-z一-鿆0-9０-９ぁ-ヶｦ-ﾟー]+/, '')%>
            <% hashs.each do |hash|%>
                <% hash.sub!(/[#＃]/, '')%>
                <%= link_to "##{hash}", root_path(hashtag: hash) %>
            <% end%>
        <% else%>
            <%= post.impressions%>
        <% end%>
    </li>
    <li class="list-group-item ramen-image" id="list4">
        <%= image_tag post.image, class: 'ra-ime'%>
        <h3 class="ramen-image-genre"><%= post.genre.genre_name%></h3>
    </li>
    <li class="list-group-item" id="list5">
        <%= link_to "コメント", noodle_path(post.id), method: :get, class: "btn btns"%>
        <% if user_signed_in? && current_user.id == post.user_id %>
            <%= link_to "削除",noodle_path(id: post.id), method: :delete, class: "btn btns" %>
        <% end %>
        <%= render partial: 'shared/like_form',locals:{post: post} %>
    </li>
        
</ul>

app/views/shared/_profile.html.erb
<div class="col-md-3 col-sm-3 col-xs-3 top">
    <% if user_signed_in?%>
        <div class="thumbnail profile">
            <%= image_tag current_user.avatar,:class => "icon" %>
            <div class="caption">
                <% @user ||= current_user %>
                <h3><%= @user.nickname%><span>さん</span></h3>
                <p><span>投稿数：</span>
                    <strong class="stat">
                        <%= Post.where(user_id: @user.id).count %>
                    </strong>
                </p>
                <p><span>フォロー数：</span>
                    <a href="<%= following_user_path(@user) %>">
                        <strong id="following" class="stat">
                            <%= @user.followings.count %>人
                        </strong>
                    </a>
                </p>
                <p><span>フォロワー数：</span>
                    <a href="<%= followers_user_path(@user) %>">
                        <strong id="followers" class="stat">
                            <%= @user.followers.count %>人
                        </strong>
                    </a>
                </p>
                <ul>
                    <li>
                        <a href="users/<%=current_user.id%>" class="btn btns">マイページ</a>
                        <a href="noodles/new" class="btn  btns">投稿する</a>
                    </li>
                    <li>
                        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn"%>
                    </li>
                </ul>
            </div><!-- /.caption -->
        </div><!-- /.thumbnail -->
    <% else%>
        <div class="thumbnail profile">
            <%= image_tag "logo.png",:class => "icon" %>
            <div class="caption">
                <h3>ログインしよう！</h3>
                <p><%= link_to "新規登録", new_user_registration_path, class: "btn btns" %>
                <%= link_to "ログイン", user_session_path, method: :post, class: "btn btns" %></p>
            </div><!-- /.caption -->
        </div><!-- /.thumbnail -->
      <%end%>
      <!-- 画面幅が991pxいかになったらプロフィールにしたに表示-->
    <div class="min_rank">
        <%= render partial: 'shared/ranking' %>
    </div>
</div>

app/views/shared/_ranking.html.erb
<ul class="list-group list-rank">
	<% if @top_five.size > 5%>
  	<li class="list-group-item title">いいね数ランキング</li>
		<li class="list-group-item">
			<%= link_to noodle_path(@top_five[0].id), method: :get do %>
				<%= image_tag @top_five[0].image, class: 'ranking-ime'%>
				<h2 class="ramen-image-title">1位</h2>
			<% end%>
		</li>
		<li class="list-group-item">
			<%= link_to noodle_path(@top_five[1].id), method: :get do %>
				<%= image_tag @top_five[1].image, class: 'ranking-ime'%>
				<h2 class="ramen-image-title">2位</h2>
			<% end%>
		</li>
		<li class="list-group-item">
			<%= link_to noodle_path(@top_five[2].id), method: :get do %>
				<%= image_tag @top_five[2].image, class: 'ranking-ime'%>
				<h2 class="ramen-image-title">3位</h2>
			<% end%>
		</li>
		<li class="list-group-item">
			<%= link_to noodle_path(@top_five[3].id), method: :get do %>
				<%= image_tag @top_five[3].image, class: 'ranking-ime'%>
				<h2 class="ramen-image-title">4位</h2>
			<% end%>
		</li>
		<li class="list-group-item">
			<%= link_to noodle_path(@top_five[4].id), method: :get do %>
				<%= image_tag @top_five[4].image, class: 'ranking-ime'%>
				<h2 class="ramen-image-title">5位</h2>
			<% end%>
		</li>
	<% end%>
</ul>