config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'noodles#index'
  resources :noodles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/noodles_controller.rb
class NoodlesController < ApplicationController
    before_action :move_to_index, except: :index
    include NoodlesHelper
    def index
        posts = Post.includes(:user)
        @posts = sort(posts)
        if params[:hashtag]
            if hashtag = Hashtag.find_by(hashname: params[:hashtag])
                hashtagpost = HashtagPost.where(hashtag_id: hashtag.id)
                posts = []
                hashtagpost.each do |hp|
                    id = hp.post_id
                    post = Post.find(id)
                    posts << post
                end
                @posts = posts.sort_by!{|post| post.created_at}.reverse!
            else
                flash[:notice] = "該当するハッシュタグはありませんでした"
                redirect_back(fallback_location: root_path)
            end
        end
        if params[:genre]
            if params[:genre] == ""
                flash[:notice] = "ジャンルを選択してください"
            else
                posts = posts.where(genre_id: params[:genre])
                @posts = sort(posts)
            end
        end
        @like = Like.new
        @top_five = Post.includes(:user).order("likes_count DESC")
    end

    def show
        @post = Post.find(params[:id])
        @like = Like.new
        @comments = @post.comments.includes(:user)
    end

    def new
        @noodle = Post.new
    end

    def create
        @noodle = current_user.posts.build(post_params)
        if @noodle.save
            redirect_to action: :index
        else
            redirect_to action: :new
        end
    end

    def destroy
        @post = Post.find(params[:id])
        if @post.user_id == current_user.id
            @post.hashtag_posts.each do |h|
                h.delete
            end
            @post.delete
            redirect_back(fallback_location: root_path)
        end
    end

    def edit
    end

    def hashtag
        @user = current_user
        @tag = Hashtag.find_by(hashname: params[:name])
        @posts = @tag.posts.build
        @post  = @tag.posts.page(params[:page])
        @comment    = Comment.new
        @comments   = @posts.comments
    end

    private

    def post_params
        params.require(:post).permit(:impressions, :image, :genre_id)
    end

    def move_to_index
        redirect_to action: :index unless user_signed_in?
    end
end

app/helpers/noodles_helper.rb
module NoodlesHelper
    def sort(posts)    
        posts.order("created_at DESC").page(params[:page]).per(5)
    end
end

app/views/noodles/_post.html.erb
    <ul class="list-group">
        <li class="list-group-item" id="list1">
            <%= image_tag post.user.avatar,:class => "icon", :size => "50x50"%>
            <%= post.user.nickname%>
        </li>
        <li class="list-group-item" id="list3"><%=post.impressions%></li>
        <li class="list-group-item ramen-image" id="list4">
            <%= image_tag post.image, class: 'ra-ime'%>
            <h3 class="ramen-image-genre"><%= post.genre.genre%></h3>
        </li>
        <li class="list-group-item" id="list5">
            <a href="#" class="btn btns">いいね！</a>
            <a href="#" class="btn   btns">コメント</a>
            <a href="#" class="btn   btns">マップ</a>
        </li>
    </ul>

app/views/noodles/edit.html.erb
<h1>Noodles#edit</h1>
<p>Find me in app/views/noodles/edit.html.erb</p>

app/views/noodles/index.html.erb
<div id="index">
  <!-- headerバー -->
  <%= render partial: 'shared/header' %>
  <!-- </nav> -->
  <div class="container main bg-warning">
    <div class="row content">
      <!-- left-contents -->
      <%= render partial: 'shared/profile' %>
      <!-- senter-contents -->
    <div class="col-md-6 col-sm-9 col-xs-9">
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
      <% @posts.each do |post| %>
          <%= render partial: 'shared/post',locals:{post: post}  %>
      <% end %>
      <% unless params[:hashtag]%>
        <%= paginate(@posts) %>
      <% end%>
    </div>
  <!-- 画面幅が991px以上になったら右側に表示　-->
    <div class="col-md-3  rank">
      <%= render partial: 'shared/ranking' %>
    </div>
  </div>
</div>

app/views/noodles/new.html.erb
<div class="container-fluid head">
    <a class="navbar-brand" href="/">
        <%= image_tag "logo.png", size: "60x60", class: "logo" %>
    </a>
</div>
<div id="post_new" >
  <div class="content container">
    <%= form_with(model: [@noodle], url: noodles_path) do |f| %>
      <%= f.label :image, class: 'label-block' do %>
        <i class="fas fa-plus fa-3x"></i>
        <p>画像を選択</p>
        <%= f.file_field :image, class: 'hidden', "v-on:change" => "handlechange"%>
      <% end %>
      <div class="genre-select">
        <%= f.select :genre_id, [["豚骨",  1], ["家系",  2],["二郎",  3], ["まぜそば",  4],
               ["つけ麺",  5], ["醤油", 6],["みそ",  7], ["塩",  8],["タンメン",  9],["その他", 10]], "v-model": "ragen" %>
      </div>
      <div class="image-place">
        <div v-if="preview" class="ramen-image">
          <img v-bind:src="preview" class="new-image img-rounded"/>
        </div>
      </div>
      <label class = "form-item review-form">
        <%= f.text_area :impressions ,class: "review", placeholder: "とても美味しい〜！ #noodle屋" %>
      </label>
      <div class="btn-place">
        <%= f.submit "注文", class: "btn btn-ramen" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  var app = new Vue({
    el: '#post_new',
    data:{
      preview: '',
    },
    methods: {
      handlechange: function(event){
        var file = event.target.files[0]
        if (file && file.type.match(/^image\/(png|jpeg)$/)){
          this.preview = window.URL.createObjectURL(file)
        }
      }
    }
  })
</script>

app/views/noodles/show.html.erb
<div id="post_show">
    <div class="container-fluid head">
        <a class="navbar-brand" href="/">
            <%= image_tag "logo.png", size: "60x60", class: "logo" %>
        </a>
    </div>
    <div class="show-field container">
        <div class="row">
            <ul class="list-group post col-md-6 col-sm-6 col-xs-6">
                <li class="list-group-item" id="list1">
                    <%= link_to user_path(id: @post.user.id) do%>
                        <%= image_tag @post.user.avatar,:class => "icon", :size => "50x50"%>
                        <%= @post.user.nickname %>
                    <% end%>
                </li>
                <li class="list-group-item" id="list3"><%= @post.impressions%></li>
                <li class="list-group-item ramen-image" id="list4">
                    <%= image_tag @post.image, class: 'ra-ime'%>
                    <h3 class="ramen-image-genre"><%= @post.genre.genre_name%></h3>
                </li>
                <li class="list-group-item" id="list5">
                    <%= render partial: 'shared/like_form',locals:{post: @post} %>
                </li>
            </ul>
            <div class="comments-field col-md-6 col-sm-6 col-xs-6">
                <div class="comments">
                    <% if @comments %>
                        <% @comments.each do |comment| %>
                            <p class="comm">
                                <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                                <%= comment.text %>
                                <% if user_signed_in? && current_user.id == comment.user_id %>
                                    <a>
                                        <%= link_to "削除",noodle_comment_path(noodle_id: @post.id, id: comment.id), method: :delete %>
                                    <a>
                                <% end %>
                            </p>
                    <% end %>
                <% end %>
                </div>
                <div class="comment-form-field">
                    <div class="comment-form">
                        <%= form_with model: @comment, url: noodle_comments_path(noodle_id: @post.id) do |f| %>
                            <%= f.text_field :text, placeholder: "コメント(50文字以内)", maxlength: "50", class: "form"%>
                            <%= f.submit "送信", class: "btn btns"%>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>